services:
  - type: web
    name: fastapi-vehicle-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn vehicle_api:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000
